PR for review
t-rex777/june pull request #1
Opened 2021-07-02 16:59 UTC by t-rex777

Name : Manish kumar Sahu
Live Link : https://june-social.netlify.app/

2021-07-03 18:05 UTC, kushanksriraj requested changes

2021-07-03 18:05 UTC, kushanksriraj commented on packages/app/src/App.tsx
> +export const PrivateRoute = (props: PrivateProps) => {
You can extract this to a new file so that your code will be more modular and easy to debug

2021-07-03 18:05 UTC, kushanksriraj commented on packages/app/src/App.tsx
> +interface PrivateProps {
Better to keep all the types in one file.

2021-07-03 18:05 UTC, kushanksriraj commented on packages/app/src/base/SearchBox.js
> +import React, { useEffect, useState } from "react";
This file also contains JSX, so better to rename it with `.jsx`

2021-07-03 18:05 UTC, kushanksriraj commented on packages/app/src/features/userAuth/components/EditUser.tsx
> +    user &&
It's better to use if condition when the statements span across multiple lines.

2021-07-03 18:05 UTC, kushanksriraj commented on packages/app/src/features/userAuth/pages/Feed.js
> +/* eslint-disable no-unused-vars */
If you are using TS for your project then keep all the files in `.ts` or `.tsx` extension.

2021-07-18 16:45 UTC, t-rex777 commented on packages/app/src/App.tsx
> +export const PrivateRoute = (props: PrivateProps) => {
Thanks, I will do that

2021-07-18 16:46 UTC, t-rex777 commented on packages/app/src/App.tsx
> +interface PrivateProps {
yes, I missed it

2021-07-18 16:47 UTC, t-rex777 commented on packages/app/src/features/userAuth/components/EditUser.tsx
> +    user &&
can you explain it, didn't get it

2021-07-18 16:48 UTC, t-rex777 commented on packages/app/src/features/userAuth/pages/Feed.js
> +/* eslint-disable no-unused-vars */
yes, I did that, but Cloudinary doesn't support typescript, so I had to make some files in javascript.

2021-08-30 14:48 UTC, merged